config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'profiles/show'
  root to: 'posts#index'
  resources :likes
  resources :comments
  resources :posts do
    resources :comments
    collection do
      get :search
    end
  end
  resources :profiles, only: [:show]
  resources :notifications, only: [:index]
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_one_attached :image

    validates :title, :body ,presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  has_many :likes
  has_one_attached :avatar
  has_many :notifications, dependent: :destroy

  enum role: { user: 'user', admin: 'admin', moderator: 'moderator' }

  validates :username, :email ,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authorize_user

  def index
    @categories = Category.where(status: true)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.status = current_user&.role == "user" ? true : @category.status
    @category.save
      redirect_to categories_path, notice: "Category was successfully created."
  end

  def update
    @category.update(category_params)
    @category.status = current_user&.role == "user" ? true : @category.status
      redirect_to categories_path, notice: "Category was successfully updated."
  end

  def destroy
    @category.destroy!
      redirect_to categories_path, notice: "Category was successfully destroyed."
  end

  private

    def authorize_user
      unless current_user&.admin? || current_user&.moderator?
        redirect_to root_url, alert: "You are not authorized to perform this action."
      end
    end

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:title, :description, :status)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: %i[ show edit update destroy ]

  def index
    @comments = Comment.where(status: true)
  end

  def show
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    @comment.status = current_user&.role == "user" ? true : @comment.status

    if @comment.save
      create_notification(@post.user, @comment)
      redirect_to @post, notice: 'Comment was successfully created.'
    else
      render 'posts/show'
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.status = current_user&.role == "user" ? true : @comment.status
    @comment.update(comment_params)
      redirect_to @comment.post, notice: "Comment was successfully updated."
  end

  def destroy
    post = @comment.post
    @comment.destroy!
    redirect_to post, notice: "Comment was successfully destroyed."
  end

  private
    def create_notification(recipient, comment)
      Notification.create(user: recipient, body: "#{comment.user.username} commented on your post: #{comment.post.title}")
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:content, :user_id, :post_id, :status)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = Like.find_or_initialize_by(user_id: current_user.id, post_id: params[:post_id])
    if @like.persisted?
      @like.destroy
    else
      @like.save
    end
    redirect_to request.referrer || root_path
  end

  private
    def set_like
      @like = Like.find(params[:id])
    end

    def like_params
      params.require(:like).permit(:user_id, :post_id)
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = current_user.notifications.order(created_at: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.where(status: true)
    @comments = Comment.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.status = current_user&.role == "user" ? true : @post.status

    @post.save
      redirect_to post_url(@post), notice: "Post was successfully created."
  end

  def update
      @post.status = current_user&.role == "user" ? true : @post.status
      @post.update(post_params)
        redirect_to post_url(@post), notice: "Post was successfully updated."
  end

  def destroy
    @post.destroy!
    redirect_to posts_url, notice: "Post was successfully destroyed."
  end

  def search
    @search_term = params[:search_term]
    @posts = Post.where("title LIKE ?", "%#{@search_term}%")

    render :index
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, :image, :user_id, :status, :category_id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Title:</strong>
    <%= category.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= category.description %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= category.status %>
  </p>

</div>

app/views/categories/_form.html.erb
<div class="container mt-4 d-flex align-items-center">
  <div class="mx-auto col-md-8 col-lg-6">
    <%= form_with(model: category, class: "form") do |form| %>
      <% if category.errors.any? %>
        <div class="alert alert-danger">
          <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
          <ul>
            <% category.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= form.label :title, class: "form-label text-white" %>
        <%= form.text_field :title, class: "form-control input-transparent text-white" %>
      </div>

      <div class="mb-3">
        <%= form.label :description, class: "form-label text-white" %>
        <%= form.text_field :description, class: "form-control input-transparent text-white" %>
      </div>

      <div class="mb-3">
        <div class="form-check">
          <%= form.label :status, class: "form-check-label text-white" %>
          <%= form.check_box :status, class: "form-check-input text-white" %>
        </div>
      </div>

      <div class="mb-3">
        <%= form.submit "Save", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>
<style>
  .input-transparent {
  background: #243439;
  border-width: 0;
  color: white;
  }

  .input-transparent:focus {
  background: #243439;
  border-width: 0;
  color: white;
  }

  .input-transparent::placeholder {
    color: white;
  }
</style>

app/views/categories/edit.html.erb
<%= render "form", category: @category %>

app/views/categories/index.html.erb
<div class="container mt-4 d-flex align-items-center">
  <div class="mx-auto col-md-8 col-lg-10">

    <h1 class="text-white">Categories</h1>

    <div class="mb-3">
      <%= link_to "New category", new_category_path, class: "btn btn-primary" %>
    </div>

    <div class="table-responsive">
      <table class="table table-dark">
        <thead class="input-transparent">
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td><%= category.title %></td>
              <td><%= category.description %></td>
              <td><%= category.status ? "Active" : "Inactive" %></td>
              <td>
                <%= link_to "Edit", edit_category_path(category), class: "btn btn-primary btn-sm me-2" %>
                <%= link_to "Delete", category, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary btn-sm" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<style>
  body {
    background-color: #243439
  }

  .container {
    padding-top: 20px;
  }

  .btn {
    color: #fff;
  }

  .input-transparent {
  background: #243439;
  border-width: 0;
  color: white;
  }

  .input-transparent:focus {
  background: #243439;
  border-width: 0;
  color: white;
  }

  .input-transparent::placeholder {
    color: white;
  }
</style>

app/views/categories/new.html.erb
<%= render "form", category: @category %>

app/views/categories/show.html.erb
<%= render @category %>

<div class="mt-3">
  <%= link_to "Edit this category", edit_category_path(@category), class: "btn btn-warning me-2" %>
  <%= link_to "Back to categories", categories_path, class: "btn btn-secondary" %>

  <%= button_to "Destroy this category", @category, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger ms-2", style: "white-space: nowrap;" %>
</div>

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <%= comment.content %>
  </p>
<% if current_user.role == "admin" %>
  <p>
    <strong>Status:</strong>
    <%= comment.status %>
  </p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, class: 'my-4') do |form| %>
  <% if comment.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_field :content, class: "form-control input-transparent", required: true %>
  </div>

  <% if current_user.role == "admin" %>
    <div class="mb-3">
      <%= form.label :status, class: "form-check-label" %>
      <%= form.check_box :status, class: "form-check-input" %>
    </div>
  <% end %>

  <div>
    <%= form.submit class: "btn btn-secondary mt-2" %>
  </div>
<% end %>
<style>
  .input-transparent {
  background: #0b1416;
  border-width: 0;
  color: white;
  }

  .input-transparent:focus {
  background: #0b1416;
  border-width: 0;
  color: white;
  }

  .input-transparent::placeholder {
    color: white;
  }
</style>

app/views/comments/_index.html.erb
<div class="custom-card mb-3">
  <div class="custom-card-body bg-color-2 text-white">
    <h5 class="card-title">Comments</h5>
    <div id="comments">
      <% @comments.each do |comment| %>
        <div class="comment mb-3 pb-3">
          <hr>
          <p class="comment-info">
            <% if comment.user.avatar.present? %>
                  <%= image_tag(comment.user.avatar, class: "avatar-img avatar-small") %>
                <% else %>
                  <%= image_tag("default-avatar.png", class: "avatar-img avatar-small") %>
                <% end %>
            <strong>
              <%= link_to comment.user.username, profile_path(comment.user), class: "custom-link" if comment.user %>
            </strong>
            • <%= time_ago_in_words(comment.created_at) %> ago
          </p>
          <div class="comment-content" id="comment-content-<%= comment.id %>">
            <%= render comment %>
          </div>
          <div id="edit-comment-form-container-<%= comment.id %>" style="display: none;">
            <%= render 'comments/form', comment: comment %>
          </div>
          <% if current_user.id == @post.user_id || current_user.role == "admin" %>
            <div class="d-flex justify-content-between" >
              <%= link_to "Edit", "javascript:void(0);", class: "btn btn-dark mr-2 edit-comment-button", id: "edit-comment-button-#{comment.id}" %>
              <%= button_to "Destroy comment", comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-dark" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="mt-3">
      <%= form_for([@post, Comment.new], url: post_comments_path(@post), method: :post) do |f| %>
        <div class="form-group">
          <%= f.text_area :content, class: "form-control input-transparent", placeholder: "Enter your comment here", rows: 2, required: true %>
        </div>
        <%= f.submit "Create Comment", class: "btn btn-secondary mt-2" %>
      <% end %>
    </div>
  </div>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const editCommentButtons = document.querySelectorAll(".edit-comment-button");

    if (editCommentButtons) {
      editCommentButtons.forEach(function (button) {
        button.addEventListener("click", function () {
          const commentId = button.id.split("-").pop();

          const commentContent = document.getElementById(`comment-content-${commentId}`);
          if (commentContent) {
            commentContent.style.display = "none";
          }

          const commentFormContainer = document.getElementById(`edit-comment-form-container-${commentId}`);
          if (commentFormContainer) {
            commentFormContainer.style.display = "block";
          }
          button.style.display = "none";
        });
      });
    }
  });
</script>
<style>
  .input-transparent {
  background: #0b1416;
  border-width: 0;
  color: white;
  }

  .input-transparent:focus {
  background: #0b1416;
  border-width: 0;
  color: white;
  }

  .input-transparent::placeholder {
    color: white;
  }
</style>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/likes/_form.html.erb
<%= form_with(model: like) do |form| %>
  <% if like.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
        <% like.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.check_box :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/likes/_like.html.erb
<div id="<%= dom_id like %>">
</div>

app/views/likes/edit.html.erb
<h1>Editing like</h1>

<%= render "form", like: @like %>

<br>

<div>
  <%= link_to "Show this like", @like %> |
  <%= link_to "Back to likes", likes_path %>
</div>

app/views/likes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Likes</h1>

<div id="likes">
  <% @likes.each do |like| %>
    <%= render like %>
    <p>
      <%= link_to "Show this like", like %>
    </p>
  <% end %>
</div>

<%= link_to "New like", new_like_path %>

app/views/likes/new.html.erb
<h1>New like</h1>

<%= render "form", like: @like %>

<br>

<div>
  <%= link_to "Back to likes", likes_path %>
</div>

app/views/likes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @like %>

<div>
  <%= link_to "Edit this like", edit_like_path(@like) %> |
  <%= link_to "Back to likes", likes_path %>

  <%= button_to "Destroy this like", @like, method: :delete %>
</div>

app/views/posts/_form.html.erb
<div class="container mt-4 d-flex align-items-center">
  <div class="mx-auto col-md-8 col-lg-6">
    <%= form_with(model: post) do |form| %>
      <% if post.errors.any? %>
        <div class="alert alert-danger">
          <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% post.errors.full_messages.each do |error| %>
              <li><%= error %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :title, class: "font-weight-bold text-white" %>
        <%= form.text_field :title, class: "form-control input-transparent text-white", placeholder: "Enter the title", required: true %>
      </div>

      <div class="form-group">
        <%= form.label :body, class: "font-weight-bold text-white" %>
        <%= form.text_area :body, class: "form-control input-transparent text-white", placeholder: "Enter the body", required: true %>
      </div>

      <div class="form-group col-md-6">
        <%= form.label :category_id, "Category", class: "control-label text-white" %>
        <%= form.select :category_id, options_for_select(Category.all.map { |c| [c.title, c.id] }), { prompt: "Select a category" }, class: "form-control input-transparent", required: true %>
      </div>

      <div class="form-group">
        <%= form.label :image, class: "font-weight-bold text-white" %>
        <div class="custom-file">
          <%= form.file_field :image, class: "custom-file-input text-white", id: "customFile" %>
          <%= form.label :image, class: "custom-file-label text-white", for: "customFile" %>
        </div>
      </div>

      <% if current_user.role == 'admin' %>
        <div class="form-group form-check text-white">
        <%= form.check_box :status, class: "form-check-input text-white" %>
        <%= form.label :status, class: "form-check-label" %>
      </div>
      <% end %>

      <div class="form-group">
        <%= form.submit class: "btn btn-secondary mt-2 text-white" %>
      </div>
    <% end %>
  </div>
</div>
<style>
  .input-transparent {
  background: #243439;
  border-width: 0;
  color: white;
  }

  .input-transparent:focus {
  background: #243439;
  border-width: 0;
  color: white;
  }

  .input-transparent::placeholder {
    color: white;
  }
</style>

app/views/posts/_form_edit.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :title, class: "font-weight-bold text-white" %>
    <%= form.text_field :title, class: "form-control input-transparent", placeholder: "Enter the title", required: true %>
  </div>
  <div class="form-group">
    <%= form.label :body, class: "font-weight-bold text-white" %>
    <%= form.text_area :body, class: "form-control input-transparent", placeholder: "Enter the body", required: true %>
  </div>
  <div class="form-group col-md-6">
    <%= form.label :category_id, "Category", class: "control-label text-white" %>
    <%= form.select :category_id, options_for_select(Category.all.map { |c| [c.title, c.id] }), { prompt: "Select a category" }, class: "form-control input-transparent", required: true %>
  </div>
  <div class="form-group">
    <%= form.label :image, class: "font-weight-bold text-white" %>
    <div class="custom-file">
      <%= form.file_field :image, class: "custom-file-input text-white", id: "customFile" %>
      <%= form.label :image, class: "custom-file-label text-white", for: "customFile" %>
    </div>
  </div>
  <% if current_user.role == 'admin' %>
    <div class="form-group form-check text-white">
      <%= form.check_box :status, class: "form-check-input text-white" %>
      <%= form.label :status, class: "form-check-label" %>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.submit class: "btn btn-secondary mt-2 text-white" %>
  </div>
<% end %>
<style>
  .input-transparent {
  background: #0b1416;
  border-width: 0;
  color: white;
  }

  .input-transparent:focus {
  background: #0b1416;
  border-width: 0;
  color: white;
  }

  .input-transparent::placeholder {
    color: white;
  }
</style>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="post-container">
  <p>
    <strong class="post-title">
      <%= post.title %>
    </strong>
  </p>
  <hr>
  <p>
    <%= post.body %>
  </p>

  <% if post.image.attached? %>
  <p>
    <%= image_tag post.image, class: "post-image" %>
  </p>
<% end %>

  <% if current_user && current_user.role == "admin" %>
    <p>
      <strong>Status:</strong>
      <%= post.status %>
    </p>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container mt-4">
  <div class="custom-card mb-3">
    <h1 class="mb-4 text-white">Posts</h1>
    <div id="posts">
      <% @posts.each do |post| %>
        <div class="custom-card mb-3">
          <%= link_to post, class: "text-decoration-none text-dark" do %>
            <div class="custom-card-body bg-color-2 text-white">
              <p class="post-info">
                <% if post.user.avatar.present? %>
                  <%= image_tag(post.user.avatar, class: "avatar-img avatar-small") %>
                <% else %>
                  <%= image_tag("default-avatar.png", class: "avatar-img avatar-small") %>
                <% end %>
                <strong><%= post.user.username if post.user %></strong> • <%= time_ago_in_words(post.created_at) %> ago
                <% if post.category %>
                  • <span class="post-category" style="color: #168fff;"><%= post.category.title %></span>
                <% end %>
              </p>
              <%= render post %>
            </div>
          <% end %>
          <div class="custom-card-footer d-flex justify-content-between align-items-center bg-color-2">
            <%= link_to post, class: "btn btn-primary mr-2 rounded-pill" do %>
              <span class="fas fa-comment"></span> <%= post.comments.count %>
            <% end %>
            <%= button_to({ controller: 'likes', action: 'create', post_id: post.id }, method: :post, class: "btn btn-primary mr-2 rounded-pill") do %>
              <span class="fas fa-arrow-up"></span> <%= post.likes.count %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<style>
  .post-category {
    font-weight: bold;
  }
</style>

app/views/posts/new.html.erb
<%= render "form", post: @post %>

<br>

<div>

</div>

app/views/posts/show.html.erb
<div class="container mt-4">
  <div class="custom-card mb-3">
    <div class="custom-card-body bg-color-2 text-white">
      <p class="post-info">
        <% if current_user.avatar.present? %>
          <%= image_tag(current_user.avatar, class: "avatar-img avatar-small") %>
        <% else %>
          <%= image_tag("default-avatar.png", class: "avatar-img avatar-small") %>
        <% end %>
        <strong><%= link_to @post.user.username, profile_path(@post.user), class: "custom-link" if @post.user %></strong> • <%= time_ago_in_words(@post.created_at) %> ago
        <% if @post.category %>
          • <span class="post-category" style="color: #168fff;"><%= @post.category.title %></span>
        <% end %>
      </p>
      <div id="post-container">
        <%= render @post %>
      </div>
      <div id="edit-post-form-container" style="display: none;">
        <%= render 'posts/form_edit', post: @post %>
      </div>
      <div class="mt-3 d-flex justify-content-between">
        <% if current_user.id == @post.user_id || current_user.role == "admin" %>
          <%= link_to "Edit", "javascript:void(0);", class: "btn btn-dark mr-2", id: "edit-post-button" %>
          <%= button_to "Destroy post", @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-dark" %>
        <% end %>
      </div>
    </div>
  </div>
  <%= render partial: 'comments/index', locals: { comments: @comments } %>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const editButton = document.getElementById("edit-post-button");
    const editFormContainer = document.getElementById("edit-post-form-container");
    const postContainer = document.getElementById("post-container");

    if (editButton && editFormContainer && postContainer) {
      editButton.addEventListener("click", function () {
        editFormContainer.style.display = "block";
        postContainer.style.display = "none";
        editButton.style.display = "none";
      });
    }
  });
</script>
<style>
  .post-category {
    font-weight: bold;
  }
</style>