config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'profiles/show'
  root to: 'posts#index'
  resources :likes
  resources :comments
  resources :posts do
    resources :comments
    collection do
      get :search
    end
  end
  resources :profiles, only: [:show]
  resources :notifications, only: [:index]
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_one_attached :image

    validates :title, :body ,presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  has_many :likes
  has_one_attached :avatar
  has_many :notifications, dependent: :destroy

  enum role: { user: 'user', admin: 'admin', moderator: 'moderator' }

  validates :username, :email ,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authorize_user

  def index
    @categories = Category.where(status: true)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.status = current_user&.role == "user" ? true : @category.status
    @category.save
      redirect_to categories_path, notice: "Category was successfully created."
  end

  def update
    @category.update(category_params)
    @category.status = current_user&.role == "user" ? true : @category.status
      redirect_to categories_path, notice: "Category was successfully updated."
  end

  def destroy
    @category.destroy!
      redirect_to categories_path, notice: "Category was successfully destroyed."
  end

  private

    def authorize_user
      unless current_user&.admin? || current_user&.moderator?
        redirect_to root_url, alert: "You are not authorized to perform this action."
      end
    end

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:title, :description, :status)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: %i[ show edit update destroy ]

  def index
    @comments = Comment.where(status: true)
  end

  def show
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    @comment.status = current_user&.role == "user" ? true : @comment.status

    if @comment.save
      create_notification(@post.user, @comment)
      redirect_to @post, notice: 'Comment was successfully created.'
    else
      render 'posts/show'
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.status = current_user&.role == "user" ? true : @comment.status
    @comment.update(comment_params)
      redirect_to @comment.post, notice: "Comment was successfully updated."
  end

  def destroy
    post = @comment.post
    @comment.destroy!
    redirect_to post, notice: "Comment was successfully destroyed."
  end

  private
    def create_notification(recipient, comment)
      Notification.create(user: recipient, body: "#{comment.user.username} commented on your post: #{comment.post.title}")
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:content, :user_id, :post_id, :status)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = Like.find_or_initialize_by(user_id: current_user.id, post_id: params[:post_id])
    if @like.persisted?
      @like.destroy
    else
      @like.save
    end
    redirect_to request.referrer || root_path
  end

  private
    def set_like
      @like = Like.find(params[:id])
    end

    def like_params
      params.require(:like).permit(:user_id, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.where(status: true)
    @comments = Comment.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.status = current_user&.role == "user" ? true : @post.status

    @post.save
      redirect_to post_url(@post), notice: "Post was successfully created."
  end

  def update
      @post.status = current_user&.role == "user" ? true : @post.status
      @post.update(post_params)
        redirect_to post_url(@post), notice: "Post was successfully updated."
  end

  def destroy
    @post.destroy!
    redirect_to posts_url, notice: "Post was successfully destroyed."
  end

  def search
    @search_term = params[:search_term]
    @posts = Post.where("title LIKE ?", "%#{@search_term}%")

    render :index
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, :image, :user_id, :status, :category_id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light justify-content-evenly bg-color-2">
  <div>
    <div class="collapse navbar-collapse" id="navbarNav">
      <%= link_to "PontoCivico", root_path, class: "navbar-brand font-weight-bold text-white" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to new_post_path, class: "text-white btn btn-outline-secondary rounded-pill" do %>
            <i class="fas fa-plus"></i>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <div style="width: 30%;">
    <form class="form-inline" action="<%= search_posts_path %>" method="get">
      <div class="input-group">
        <input type="text" class="form-control rounded rounded-pill text-color" style="background-color: #0b1416; border: 0; color: white; placeholder:white;" placeholder="Pesquisar" aria-label="Search" aria-describedby="search-addon" name="search_term">
        <div class="input-group-append mx-2">
          <button class="btn btn-outline-secondary rounded-pill" type="submit" id="search-addon">
            <i class="fa fa-search"></i>
          </button>
        </div>
      </div>
    </form>
  </div>
  <div class="d-flex">
    <% if current_user&.admin? || current_user&.moderator? %>
      <%= link_to "Categorias", categories_path, class: "btn btn-primary rounded-pill mr-2" %>
    <% end %>
    <% if current_user %>
      <%= link_to notifications_path(current_user), class: "btn btn-primary rounded-pill mr-2" do %>
      <i class="fas fa-bell"></i>
      <% end %>
    <%= link_to profile_path(current_user), class: "btn btn-primary rounded-pill mr-2" do %>
      <% if current_user.avatar.present? %>
        <%= image_tag(current_user.avatar, class: "avatar-img avatar-small") %>
      <% else %>
        <%= image_tag("default-avatar.png", class: "avatar-img avatar-small") %>
      <% end %>
      Perfil
    <% end %>
      <%= button_to "Sair", destroy_user_session_path, method: :delete, class: "btn btn-primary rounded-pill" %>
    <% else %>
      <%= button_to "Entrar", new_user_session_path, class: "btn btn-primary rounded-pill" %>
    <% end %>
  </div>
</nav>
<style>
  .text-color::placeholder {
      color: white;
    }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PontoCivico</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>



    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-color-1">

    <%= render partial: 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>